version: '3.9'

services:
  db:
    image: postgres 
    environment: 
      # - 'POSTGRES_HOST_AUTH_METHOD=trust'
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    # command: python manage.py runserver 0.0.0.0:8002
    command: gunicorn superteam.wsgi:application --bind 0.0.0.0:8005 --workers 4
    volumes:
      - .:/code
    ports:
      - "8005:8005"
    depends_on: 
      - db